// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app_services} from '../models';
import {config} from '../models';

export function GetConfig():Promise<app_services.ApiResponse_tulsu_pe_timetable_backend_config_Config_>;

export function GetConfigPath():Promise<app_services.ApiResponse_string_>;

export function UpdateConfig(arg1:config.Config):Promise<app_services.ApiResponse_bool_>;
