// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDirection(arg1) {
  return window['go']['app_services']['App']['CreateDirection'](arg1);
}

export function CreateFaculty(arg1) {
  return window['go']['app_services']['App']['CreateFaculty'](arg1);
}

export function CreateLesson(arg1) {
  return window['go']['app_services']['App']['CreateLesson'](arg1);
}

export function CreateTeacher(arg1) {
  return window['go']['app_services']['App']['CreateTeacher'](arg1);
}

export function DeleteDirection(arg1) {
  return window['go']['app_services']['App']['DeleteDirection'](arg1);
}

export function DeleteFaculty(arg1) {
  return window['go']['app_services']['App']['DeleteFaculty'](arg1);
}

export function DeleteLesson(arg1) {
  return window['go']['app_services']['App']['DeleteLesson'](arg1);
}

export function DeleteTeacher(arg1) {
  return window['go']['app_services']['App']['DeleteTeacher'](arg1);
}

export function GetConfig() {
  return window['go']['app_services']['App']['GetConfig']();
}

export function GetConfigPath() {
  return window['go']['app_services']['App']['GetConfigPath']();
}

export function GetDirections() {
  return window['go']['app_services']['App']['GetDirections']();
}

export function GetFaculties() {
  return window['go']['app_services']['App']['GetFaculties']();
}

export function GetLessons() {
  return window['go']['app_services']['App']['GetLessons']();
}

export function GetTeachers() {
  return window['go']['app_services']['App']['GetTeachers']();
}

export function UpdateConfig(arg1) {
  return window['go']['app_services']['App']['UpdateConfig'](arg1);
}

export function UpdateDirection(arg1) {
  return window['go']['app_services']['App']['UpdateDirection'](arg1);
}

export function UpdateFaculty(arg1) {
  return window['go']['app_services']['App']['UpdateFaculty'](arg1);
}

export function UpdateLesson(arg1) {
  return window['go']['app_services']['App']['UpdateLesson'](arg1);
}

export function UpdateTeacher(arg1) {
  return window['go']['app_services']['App']['UpdateTeacher'](arg1);
}
