// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storage} from '../models';
import {app_services} from '../models';
import {config} from '../models';

export function CreateDirection(arg1:storage.CreateDirectionRequest):Promise<app_services.ApiResponse_tulsu_pe_timetable_backend_storage_Direction_>;

export function CreateFaculty(arg1:storage.CreateFacultyRequest):Promise<app_services.ApiResponse_tulsu_pe_timetable_backend_storage_Faculty_>;

export function CreateLesson(arg1:storage.CreateLessonRequest):Promise<app_services.ApiResponse_tulsu_pe_timetable_backend_storage_Lesson_>;

export function CreateTeacher(arg1:storage.CreateTeacherRequest):Promise<app_services.ApiResponse_tulsu_pe_timetable_backend_storage_Teacher_>;

export function DeleteDirection(arg1:number):Promise<app_services.ApiResponse_bool_>;

export function DeleteFaculty(arg1:number):Promise<app_services.ApiResponse_bool_>;

export function DeleteLesson(arg1:number):Promise<app_services.ApiResponse_bool_>;

export function DeleteTeacher(arg1:number):Promise<app_services.ApiResponse_bool_>;

export function GetConfig():Promise<app_services.ApiResponse_tulsu_pe_timetable_backend_config_Config_>;

export function GetConfigPath():Promise<app_services.ApiResponse_string_>;

export function GetDirections():Promise<app_services.ApiResponse___tulsu_pe_timetable_backend_storage_Direction_>;

export function GetFaculties():Promise<app_services.ApiResponse___tulsu_pe_timetable_backend_storage_Faculty_>;

export function GetLessons():Promise<app_services.ApiResponse___tulsu_pe_timetable_backend_storage_Lesson_>;

export function GetTeachers():Promise<app_services.ApiResponse___tulsu_pe_timetable_backend_storage_Teacher_>;

export function UpdateConfig(arg1:config.Config):Promise<app_services.ApiResponse_bool_>;

export function UpdateDirection(arg1:storage.UpdateDirectionRequest):Promise<app_services.ApiResponse_tulsu_pe_timetable_backend_storage_Direction_>;

export function UpdateFaculty(arg1:storage.UpdateFacultyRequest):Promise<app_services.ApiResponse_tulsu_pe_timetable_backend_storage_Faculty_>;

export function UpdateLesson(arg1:storage.UpdateLessonRequest):Promise<app_services.ApiResponse_tulsu_pe_timetable_backend_storage_Lesson_>;

export function UpdateTeacher(arg1:storage.UpdateTeacherRequest):Promise<app_services.ApiResponse_tulsu_pe_timetable_backend_storage_Teacher_>;
