// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['app_services']['App']['GetConfig']();
}

export function GetConfigPath() {
  return window['go']['app_services']['App']['GetConfigPath']();
}

export function UpdateConfig(arg1) {
  return window['go']['app_services']['App']['UpdateConfig'](arg1);
}
